name: 'Upload to R2'
description: 'Upload file to Cloudflare R2'

inputs:
  file:
    required: true
    description: 'File to upload'
  r2-path:
    required: true
    description: 'Path in R2 bucket'

runs:
  using: "composite"
  steps:
    - name: Configure rclone
      shell: bash
      run: |
        mkdir -p ~/.config/rclone
        cat > ~/.config/rclone/rclone.conf << EOF
        [r2]
        type = s3
        provider = Cloudflare
        access_key_id = ${{ env.R2_ACCESS_KEY_ID }}
        secret_access_key = ${{ env.R2_SECRET_ACCESS_KEY }}
        endpoint = ${{ env.R2_ENDPOINT }}
        region = auto
        EOF
      env:
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        
    - name: Upload to R2
      shell: bash
      run: |
        rclone copy ${{ inputs.file }} r2:${{ secrets.R2_BUCKET_NAME }}/${{ inputs.r2-path }} --progress
        rm ${{ inputs.file }}
      env:
        R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}